### ISSUE TITLE
Path moving forward?

### ISSUE THREAD

**Issue by sethvargo** [jimhopp/chefspec_exploration#6]
Hey Jim,

Do you have some time to chat? I'd like to figure out the best path for the examples in this repository moving forward.

**Comment by jimhopp** [comment]
Hi Seth-

Sure, tomorrow works.

I've just started a sabbatical, but I'm willing to revamp the repo for
chefspec3 if you think that makes sense. If you think the doc on the
chefspec repo is good enough, I'm also willing to simply mark it deprecated.

I'm available after 10am PST tomorrow.

-Jim

**Comment by sethvargo** [comment]
Hey @jimhopp 

Whatever you think is easiest. If you're on sabbatical, you shouldn't have to worry about revamping this repo :smile:
